import test from 'node:test';import assert from 'node:assert/strict';import {wblockDocument,wblockDXF,wblockFileName} from '../src/wblock.js';import {wblockTools} from '../src/wblock-tools.js';import {Editor} from '../src/editor.js';import {validDocument} from '../src/document.js';import {importDXF} from '../src/dxf-import.js';import {blockParts} from '../src/blocks.js';import {withParameterValue} from '../src/parametric-blocks.js';import {createDocumentWorkflow} from '../src/document-workflow.js';
const p=(x,y)=>({x,y}),line={id:'line',type:'line',layer:'geometry',points:[p(100,200),p(1100,200)],lineWeight:0.35,lineType:'DASHED'},layers=[{id:'0',name:'0',color:'#ffffff'},{id:'geometry',name:'Mall',color:'#12ab34',lineType:'CONTINUOUS',locked:true},{id:'unused',name:'Other',color:'#bbbbbb'}];
const source=()=>({version:1,name:'Original',layers,layouts:[{id:'paper',name:'Sheet',width:297,height:210}],entities:[line,{id:'unused',type:'circle',layer:'unused',center:p(3000,0),radius:100}]});
function smartBlock(){return {id:'block',type:'block',layer:'geometry',point:p(500,800),scale:2,rotation:Math.PI/2,mirrored:true,values:{NAME:'Instance'},definition:{id:'definition',name:'Fönster',entities:[{...line,id:'edge',points:[p(0,0),p(1000,0)]},{id:'text',type:'text',layer:'0',text:'Default',attributeTag:'NAME',height:10,point:p(1000,50),rotation:0}],stretchParameters:[{id:'width',name:'Bredd',start:p(0,0),end:p(1000,0),window:{minX:900,maxX:1100,minY:-100,maxY:100},targets:[{entityId:'edge',mode:'points',indices:[1],holes:[]},{entityId:'text',mode:'move'}]}]}};}
test('WBLOCK extracts only selected objects and required layers, with local origin and unchanged source/history',()=>{
 const doc=source(),before=JSON.stringify(doc),out=wblockDocument(doc,{name:'Mall 01.dxf',entityIds:['line'],base:p(100,200)});assert.equal(out.name,'Mall 01');assert.deepEqual(out.entities[0].points,[p(0,0),p(1000,0)]);assert.equal(out.entities[0].lineWeight,0.35);assert.equal(out.entities[0].lineType,'DASHED');assert.deepEqual(out.layers.map(l=>l.name),['0','Mall']);assert.equal(out.layouts,undefined);assert.equal(out.blocks,undefined);assert(validDocument(out));assert.equal(JSON.stringify(doc),before);
 const file=wblockDXF(doc,{name:'Mall 01',entityIds:['line'],base:p(100,200)});assert.equal(file.name,'Mall 01.dxf');assert.equal(file.count,1);assert.match(file.text,/\$INSUNITS\n70\n4\n/);assert.match(file.text,/\$INSBASE\n10\n0\n20\n0\n30\n0\n/);const roundtrip=importDXF(file.text).document;assert.equal(roundtrip.entities.length,1);assert.deepEqual(roundtrip.entities[0].points,[p(0,0),p(1000,0)]);
});
test('WBLOCK selection preserves the current smart-block shape, placement, mirror and attribute value relative to the base',()=>{
 const block=withParameterValue(smartBlock(),'width',1600),doc={...source(),entities:[block]},before=JSON.stringify(doc),base=p(500,800),file=wblockDXF(doc,{name:'Window-instance',entityIds:['block'],base}),back=importDXF(file.text).document,parts=blockParts(back.entities[0]),original=blockParts(block);assert(validDocument(back));assert.equal(parts.find(e=>e.attributeTag).text,'Instance');assert.equal(parts[0].points[1].y,3200);assert.equal(back.entities[0].definition.stretchParameters,undefined);for(let i=0;i<2;i++){assert(Math.abs(parts[0].points[i].x-(original[0].points[i].x-base.x))<1e-6);assert(Math.abs(parts[0].points[i].y-(original[0].points[i].y-base.y))<1e-6);}assert.equal(JSON.stringify(doc),before);
});
test('WBLOCK named definitions export local default geometry and ATTDEF even when the library has no inserted instance',()=>{
 const definition=smartBlock().definition,doc={...source(),blocks:[definition]},file=wblockDXF(doc,{name:'Window-definition',definitionId:definition.id}),out=importDXF(file.text).document;assert.equal(out.entities[0].points[1].x,1000);assert.equal(out.entities.find(e=>e.attributeTag).text,'Default');assert.match(file.text,/\nATTDEF\n/);assert(!file.text.includes('Other'));assert(validDocument(out));
});
test('WBLOCK translates paper geometry, hatch holes and annotation variants into model coordinates without bringing layouts',()=>{
 const text={id:'t',type:'text',layer:'geometry',space:'paper',point:p(100,200),height:10,text:'Hello',annotationVariants:[{denominator:50,entity:{id:'t',type:'text',layer:'geometry',point:p(120,210),height:5,text:'Hello'}}]},hatch={id:'h',type:'hatch',layer:'geometry',space:'paper',spacing:20,points:[p(100,200),p(200,200),p(200,300),p(100,300)],holes:[[p(110,210),p(120,210),p(120,220)]]},doc={...source(),entities:[text,hatch]},out=wblockDocument(doc,{name:'Paper-detail',entityIds:['t','h'],base:p(100,200)});assert(out.entities.every(e=>e.space==='model'));assert.deepEqual(out.entities[0].annotationVariants[0].entity.point,p(20,10));assert.deepEqual(out.entities[1].holes[0][0],p(10,10));assert(validDocument(out));
});
test('empty, disappeared, duplicate, viewport and invalid-filename exports fail without creating partial files',()=>{
 for(const ids of [[],['missing'],['line','line']])assert.throws(()=>wblockDocument(source(),{name:'Mall',entityIds:ids}));assert.throws(()=>wblockDocument(source(),{name:'Mall',definitionId:'missing'}));const doc=source();doc.entities.push({id:'v',type:'viewport',layer:'0',space:'paper',points:[p(0,0),p(100,100)],viewCenter:p(0,0),viewScale:1});assert.throws(()=>wblockDocument(doc,{name:'Mall',entityIds:['line','v']}),/Viewport/);for(const name of ['../mal','A/B','CON','NUL.dxf','file.','..'])assert.equal(wblockFileName(name),null);assert.equal(wblockFileName('Fönster-01.dxf'),'Fönster-01');
});
test('WBLOCK command supports preselection, command-first selection and named definitions; export failures retain the base phase',()=>{
 let ctx={entities:[],templates:[{definition:smartBlock().definition}]},fail=false;const exports=[],editor=new Editor({tools:wblockTools,getContext:()=>ctx,applyChange:c=>{if(fail)throw Error('Download failed');exports.push(c);}});editor.start('WBLOCK');editor.dispatch({type:'text',text:'O'});assert.equal(editor.state.phase,'select');ctx.entities=[line];editor.dispatch({type:'text',text:''});editor.dispatch({type:'text',text:'Mall 01'});fail=true;assert.throws(()=>editor.dispatch({type:'point',point:p(100,200)}));assert.equal(editor.state.phase,'base');fail=false;editor.dispatch({type:'text',text:'100,200'});assert.deepEqual(exports[0].entityIds,['line']);assert.deepEqual(exports[0].base,p(100,200));assert.equal(editor.state,null);
 editor.start('WBLOCK');editor.dispatch({type:'text',text:'B'});editor.dispatch({type:'text',text:'fönster'});editor.dispatch({type:'text',text:''});assert.equal(exports[1].name,'Fönster');assert.equal(exports[1].definitionId,'definition');editor.start('WBLOCK');editor.dispatch({type:'text',text:''});editor.dispatch({type:'text',text:''});editor.cancel();assert.equal(exports.length,2);
});
test('WBLOCK workflow produces a download without syncing or replacing the drawing; editing guards produce none',()=>{
 const doc=source(),downloads=[];let editing=false,textAccepted=true;const workflow=createDocumentWorkflow({getDocument:()=>doc,hasBlockEdit:()=>editing,finishText:()=>textAccepted,download:(...args)=>downloads.push(args),syncView:()=>{throw Error('Should not sync');},replaceDocument:()=>{throw Error('Should not replace');}});assert.equal(workflow.exportWblock({name:'Template',entityIds:['line'],base:p(100,200)}),1);assert.equal(downloads.length,1);assert.equal(downloads[0][0],'Template.dxf');editing=true;assert.throws(()=>workflow.exportWblock({name:'Template',entityIds:['line']}));editing=false;textAccepted=false;assert.throws(()=>workflow.exportWblock({name:'Template',entityIds:['line']}));assert.equal(downloads.length,1);
});
