// Shared command names, labels and aliases. No UI or document dependencies.
export const definitions = [
  ["LINE", "Linje", "L"],
  ["PLINE", "Polylinje", "PL"],
  ["RECTANG", "Rektangel", "REC"],
  ["CIRCLE", "Cirkel", "C"],
  ["ARC", "Båge", "A"],
  ["TEXT", "Text", "T"],
  ["LEADER", "Leader", "LE"],
  ["HATCH", "Hatch", "HA"],
  ["MOVE", "Flytta", "M"],
  ["STRETCH", "Sträck", "S"],
  ["BSTRETCH", "Blockets stretchparameter", "BSP"],
  ["COPY", "Kopiera", "CO"],
  ["ROTATE", "Rotera", "RO"],
  ["SCALE", "Skala", "SC"],
  ["MIRROR", "Spegla", "MI"],
  ["OFFSET", "Offset", "O"],
  ["ERASE", "Radera", "E"],
  ["JOIN", "Sammanfoga", "J"],
  ["EXPLODE", "Dela upp", "X"],
  ["PINSERT", "Lägg till hörn", "PI"],
  ["PDELETE", "Ta bort hörn", "PD"],
  ["FILLET", "Avrunda hörn", "F"],
  ["CHAMFER", "Fasa hörn", "CHA"],
  ["DIMLINEAR", "Linjärt mått", "DLI"],
  ["DIMALIGNED", "Riktat mått", "DAL"],
  ["DIMANGULAR", "Vinkelmått", "DAN"],
  ["DIMRADIUS", "Radiemått", "DRA"],
  ["DIMDIAMETER", "Diametermått", "DDI"],
  ["DIMCONTINUE", "Kedjemått", "DCO"],
  ["TRIM", "Trimma", "TR"],
  ["EXTEND", "Förläng", "EX"],
  ["MVIEW", "Skapa viewport", "MV"],
  ["BLOCK", "Skapa block", "B"],
  ["WBLOCK", "Exportera mall · DXF", "WB"],
  ["INSERT", "Infoga block", "I"],
  ["ATTDEF", "Attribut", "ATT"],
  ["BEDIT", "Blockeditor", "BE"],
];
export const aliases = Object.fromEntries(
  definitions.flatMap(([name, , a]) => [
    [name, name],
    [a, name],
  ]),
);
Object.assign(aliases, {
  SELECT: "SELECT",
  ESC: "SELECT",
  Z: "ZOOM",
  ZOOM: "ZOOM",
  H: "PAN",
  PAN: "PAN",
  DI: "DIST",
  DIST: "DIST",
  U: "UNDO",
  UNDO: "UNDO",
  REDO: "REDO",
  SAVE: "SAVE",
  QSAVE: "SAVE",
  DXF: "DXF",
  HELP: "HELP",
  "?": "HELP",
});

export const transforms = ["MOVE", "COPY", "ROTATE", "SCALE", "MIRROR"];
