import { referenceStatus, referenceRows, findReference } from './references.js';
export function createReferencePanel({document,root,getDocument,getProjectId=()=>null,getReason,change,chooseFile,reload,detach,bind}) {
  let selected=null,busy=false,project=null;const collapsed=new Set();
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
  const button=(text,fn,label)=>{const n=el('button',text);n.type='button';n.onclick=fn;n.setAttribute('aria-label',label || text);return n;};
  const run=async fn=>{if(busy)return;busy=true;refresh();try{await fn();}finally{busy=false;refresh();}};
  function refresh(){
    const doc=getDocument();if(project!==getProjectId()){project=getProjectId();selected=null;collapsed.clear();}
    const rows=referenceRows(doc),refs=rows.map(row=>row.reference);if(!refs.some(r=>r.id===selected))selected=refs[0]?.id;
    const selectedRow=rows.find(row=>row.reference.id===selected),r=selectedRow?.reference,nested=!!selectedRow?.parent,reason=getReason();root.replaceChildren();
    const toolbar=el('div',null,'reference-toolbar');toolbar.append(el('span',`${refs.length} ${refs.length===1?'fil':'filer'}`));
    const link=button('+ Länka filer',()=>run(()=>chooseFile()),'Länka referensfil');link.className='reference-primary';link.disabled=busy||!!reason;const folder=button('Mapp…',()=>run(()=>chooseFile(null,{folder:true})),'Välj projektmapp med referensfiler');folder.disabled=busy||!!reason;toolbar.append(link,folder);root.append(toolbar);
    if(refs.length){const batch=el('div',null,'reference-batch');for(const [text,folder,label] of [['↻ Ladda om alla…',false,'Ladda om alla referenser'],['Från mapp…',true,'Ladda om alla referenser från projektmapp']]){const b=button(text,()=>run(()=>chooseFile(null,{reloadAll:true,folder})),label);b.disabled=busy||!!reason;batch.append(b);}root.append(batch);}
    const table=el('table',null,'reference-table');table.setAttribute('aria-label','Referensfiler');
    const head=el('thead'),hr=el('tr');for(const text of ['Fil','Status','Visa']){const th=el('th',text);th.scope='col';hr.append(th);}head.append(hr);table.append(head);
    const body=el('tbody');let hiddenDepth=null;for(const {reference:ref,depth,excluded} of rows){if(hiddenDepth!=null && depth>hiddenDepth)continue;hiddenDepth=collapsed.has(ref.id)?depth:null;const row=el('tr');row.classList.toggle('selected',ref.id===selected);
      const file=el('td'),fileLabel=el('div',null,'reference-file-label');file.className='reference-file-cell';file.style.paddingLeft=`${7+depth*12}px`;row.classList.toggle('reference-excluded',excluded);if(ref.children?.length){const expand=button(collapsed.has(ref.id)?'›':'⌄',()=>{collapsed.has(ref.id)?collapsed.delete(ref.id):collapsed.add(ref.id);if(collapsed.has(ref.id))selected=ref.id;refresh();},`${collapsed.has(ref.id)?'Fäll ut':'Fäll in'} underreferenser till ${ref.name}`);expand.className='reference-expand';expand.setAttribute('aria-expanded',String(!collapsed.has(ref.id)));fileLabel.append(expand);}else fileLabel.append(el('span',null,'reference-tree-spacer'));const pick=button(ref.name,()=>{selected=ref.id;refresh();});pick.title=ref.path;pick.setAttribute('aria-pressed',String(ref.id===selected));fileLabel.append(pick);file.append(fileLabel);
      const status=el('td'),dot=el('span',null,`reference-dot ${['Saknas','Cirkulär','Tvetydig','För djup'].includes(referenceStatus(ref))?'missing':referenceStatus(ref)==='Urladdad'?'unloaded':''}`);status.append(dot,document.createTextNode(referenceStatus(ref)));
      const show=el('td'),toggle=button(ref.visible===false?'○':'◉',()=>change(ref.id,{visible:ref.visible===false},'Visa referens'),`Visa ${ref.name}`);toggle.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 12s4-6 10-6 10 6 10 6-4 6-10 6-10-6-10-6Z"/><circle cx="12" cy="12" r="3"/>'+ (ref.visible===false?'<path d="M3 21 21 3"/>':'')+'</svg>';toggle.title=ref.visible===false?'Visa referens':'Dölj referens';toggle.setAttribute('aria-pressed',String(ref.visible!==false));toggle.disabled=busy||!!reason;show.append(toggle);row.append(file,status,show);body.append(row);
    }table.append(body);const list=el('div',null,'reference-list');list.append(table);root.append(list);if(rows.some(({reference:r})=>['Saknas','Cirkulär','Tvetydig','För djup'].includes(referenceStatus(r)))){const resolve=button('Lös saknade länkar…',()=>run(()=>chooseFile(null,{resolveOnly:true})),'Lös saknade referenslänkar med flera filer');resolve.className='reference-resolve';resolve.disabled=busy||!!reason;root.append(resolve);}
    if(!r){root.append(el('p',reason||'Välj flera referensfiler eller en projektmapp. Referensen sparas i projektet och kan snappas mot.', 'reference-empty'));return;}
    const details=el('div',null,'reference-details');details.append(el('h2',r.name),el('p',`${r.name.split('.').at(-1).toUpperCase()} · ${r.kind==='overlay'?'Överlägg':'Bifoga'}${nested?' · Underreferens':''}`,'reference-subtitle'));
    const field=(label,input)=>{const wrap=el(input.tagName==='INPUT'?'label':'div',null,'reference-field');wrap.append(el('span',label),input);return wrap;};
    const path=el('input');path.setAttribute('aria-label','Sökväg');path.value=r.path;path.readOnly=true;path.title=r.path;const pathrow=el('div',null,'reference-path');const replace=button('Byt fil…',()=>run(()=>chooseFile(r.id)));replace.disabled=busy||!!reason;pathrow.append(path,replace);details.append(field('Sökväg',pathrow));
    const types=el('div',null,'reference-types');for(const [kind,label]of [['overlay','Överlägg'],['attach','Bifoga']]){const b=button(label,()=>change(r.id,{kind},'Referenstyp'));b.setAttribute('aria-label',label);b.setAttribute('aria-pressed',String(r.kind===kind));b.disabled=busy||!!reason||nested;types.append(b);}details.append(field('Referenstyp',types));
    const fade=el('input');fade.type='range';fade.min=0;fade.max=90;fade.value=r.fade;fade.setAttribute('aria-label','Nedtoning');fade.disabled=busy||!!reason||nested;const value=el('output',`${r.fade} %`);fade.oninput=()=>value.textContent=`${fade.value} %`;fade.onchange=()=>change(r.id,{fade:Number(fade.value)},'Nedtoning');const slider=el('div',null,'reference-slider');slider.append(fade,value);details.append(field('Nedtoning',slider));
    const check=el('input');check.type='checkbox';check.checked=r.snap!==false;check.disabled=busy||!!reason;check.onchange=()=>change(r.id,{snap:check.checked},'Snappa mot referens');const snap=el('label',null,'reference-snap');snap.append(check,document.createTextNode('Snappa mot referens'));details.append(snap);
    const transform=el('div',null,'reference-transform');for(const [key,label,current]of [['x','X',r.point.x],['y','Y',r.point.y],['rotation','Rotation',r.rotation*180/Math.PI],['scale','Skala',r.scale]]){const input=el('input');input.type='number';input.step='any';if(key==='scale')input.min='0.000001';input.value=Number(current.toFixed(6));input.setAttribute('aria-label',label);input.disabled=busy||!!reason||nested;input.onchange=()=>{const v=Number(input.value);if(input.value===''||!Number.isFinite(v)||key==='scale'&&v<=0){input.value=current;return;}change(r.id,key==='x'||key==='y'?{point:{...r.point,[key]:v}}:{[key]:key==='rotation'?v*Math.PI/180:v},'Placera referens');};transform.append(field(label,input));}details.append(transform);
    const actions=el('div',null,'reference-actions'),refreshButton=button('↻ Ladda om',()=>run(()=>reload(r.id)));refreshButton.disabled=busy||!!reason;actions.append(refreshButton);
    const menu=el('details',null,'reference-menu'),summary=el('summary','•••');summary.setAttribute('aria-label','Fler referensåtgärder');menu.append(summary);const menuItems=el('div',null,'reference-menu-items');for(const [text,fn]of [[r.loaded===false?'Ladda':'Urladda',()=>r.loaded===false?((r.geometry.length || r.sourceLoaded)?change(r.id,{loaded:true},'Ladda referens'):reload(r.id)):change(r.id,{loaded:false},'Urladda referens')],['Bind till ritningen',()=>bind(r.id)],['Ta bort länk',()=>detach(r.id)]]){const b=button(text,()=>run(fn));b.disabled=busy||!!reason||['Bind till ritningen','Ta bort länk'].includes(text)&&nested || text==='Bind till ritningen'&&!r.geometry.length&&!r.sourceLoaded;menuItems.append(b);}menu.append(menuItems);actions.append(menu);details.append(actions);
    const footer=busy?'Läser referensfil…':reason||(nested?(selectedRow.excluded?'Överlägg följer inte med till värdritningen.':'Placering och referenstyp kommer från källritningen.'):null)||(!r.geometry.length&&!r.sourceLoaded?'Referensfilen saknas. Välj Byt fil för att läsa in den.':`Senast inläst ${new Date(r.loadedAt||0).toLocaleTimeString('sv-SE',{hour:'2-digit',minute:'2-digit'})} · Sparad kopia i projektet`);details.append(el('p',footer,'reference-footer'));root.append(details);
  }
  return {refresh};
}
